### ISSUE TITLE
Not removing all software

### ISSUE THREAD

**Issue by shadownetdev1** [anbox/anbox-installer#13]
It is my understanding that an uninstaller is suppose to remove its software, so shouldn't ppa-purge be removed after it does it's job on lines 92 & 93?

**Comment by morphis** [comment]
@shadownetdev1 this is tricky. We would need to record if ppa-purge was already installed before the installer was executed the first time as otherwise we do something the user doesn't expect from us as he installed ppa-purge on his own rather than we did it. Another option would be that we ship ppa-purge in the snap and don't require its installation at all.

**Comment by shadownetdev1** [comment]
@morphis My suggestion would be to check for an output from [which](https://linux.die.net/man/1/which). It is installed on all Ubuntu distros and to the best of my knowledge most Linux distros

**Comment by shadownetdev1** [comment]
@morphis Updated my comment

**Comment by morphis** [comment]
@shadownetdev1 Can you propose this as PR?

**Comment by morphis** [comment]
This is now solved in master.
