### ISSUE TITLE
Unexpected "(" on line 33

### ISSUE THREAD

**Issue by spyjoshx** [anbox/anbox-installer#28]
I get this error when executing the script on Xubuntu 16.04. Any idea what the matter is?

./installer.sh: 33: ./installer.sh: Syntax error: "(" unexpected

Thanks for any help...

**Comment by chensenmo** [comment]
Hi, I got the same issue "(" on line 33. It's an script to check ur system type.
I was trying on an Ubuntu 16.04 VM, so I simply _delete those checking scripts._
I don't know much about shell script, but there may be same syntax error in this script since this project is under Alpha testing
you can try this if you **take risk on your own**... Try VM

**Comment by morphis** [comment]
This fixed already in the git tree.
