### ISSUE TITLE
KDE Neon/Neon LTS Support

### ISSUE THREAD

**Issue by GeitHub** [anbox/anbox-installer#4]
Could you please add KDE Neon/Neon LTS to the list of supported distros? KDE Neon is just the latest Ubuntu or Ubuntu LTS with the latest KDE desktop/applications added via a PPA so there's probably no compatibility issues.

Thanks

**Comment by peterchibunna** [comment]
+1

**Comment by peterchibunna** [comment]
Just to add "neon" in the array of supported distributions. I wish this can be quickly done.

**Comment by GeitHub** [comment]
hm.

Added the "neon" line to the installer and everything was going fine until it froze at the initctl line, so I did a sudo apt install upstart and reran the script, but now I'm getting:

snap "anbox" has no updates available
+ '[' '!' -e /etc/X11/Xsession.d/68anbox ']'
++ contains Ubuntu LinuxMint neon neon
++ local n=4
++ local value=neon
++ (( i=1 ))
++ (( i < 4 ))
++ '[' Ubuntu == neon ']'
++ (( i++ ))
++ (( i < 4 ))
++ '[' LinuxMint == neon ']'
++ (( i++ ))
++ (( i < 4 ))
++ '[' neon == neon ']'
++ echo y
++ return 0
+ '[' y == y ']'
+ case "$(lsb_release -r -s)" in
++ lsb_release -r -s
+ '[' '!' -e /home/user/.config/upstart/anbox.conf ']'
+ initctl start anbox
initctl: Name "com.ubuntu.Upstart" does not exist

too tired to keep playing with this now though

**Comment by peterchibunna** [comment]
Yeah. I got the same. I'm still playing around the whole thing.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: GeitHubSent: Wednesday, 12 April 2017 11:59To: anbox/anbox-installerReply To: anbox/anbox-installerCc: peterchibunna; CommentSubject: Re: [anbox/anbox-installer] KDE Neon/Neon LTS Support (#4)hm.
Added the "neon" line to the installer and everything was going fine until it froze at the initctl line, so I did a sudo apt install upstart and reran the script, but now I'm getting:
snap "anbox" has no updates available

'[' '!' -e /etc/X11/Xsession.d/68anbox ']'
++ contains Ubuntu LinuxMint neon neon
++ local n=4
++ local value=neon
++ (( i=1 ))
++ (( i < 4 ))
++ '[' Ubuntu == neon ']'
++ (( i++ ))
++ (( i < 4 ))
++ '[' LinuxMint == neon ']'
++ (( i++ ))
++ (( i < 4 ))
++ '[' neon == neon ']'
++ echo y
++ return 0
'[' y == y ']'
case "$(lsb_release -r -s)" in
++ lsb_release -r -s
'[' '!' -e /home/user/.config/upstart/anbox.conf ']'
initctl start anbox
initctl: Name "com.ubuntu.Upstart" does not exist

too tired to keep playing with this now though

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anbox/anbox-installer","title":"anbox/anbox-installer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/anbox/anbox-installer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GeitHub in #4: hm.\r\n\r\nAdded the \"neon\" line to the installer and everything was going fine until it froze at the initctl line, so I did a sudo apt install upstart and reran the script, but now I'm getting:\r\n\r\nsnap \"anbox\" has no updates available\r\n+ '[' '!' -e /etc/X11/Xsession.d/68anbox ']'\r\n++ contains Ubuntu LinuxMint neon neon\r\n++ local n=4\r\n++ local value=neon\r\n++ (( i=1 ))\r\n++ (( i \u003c 4 ))\r\n++ '[' Ubuntu == neon ']'\r\n++ (( i++ ))\r\n++ (( i \u003c 4 ))\r\n++ '[' LinuxMint == neon ']'\r\n++ (( i++ ))\r\n++ (( i \u003c 4 ))\r\n++ '[' neon == neon ']'\r\n++ echo y\r\n++ return 0\r\n+ '[' y == y ']'\r\n+ case \"$(lsb_release -r -s)\" in\r\n++ lsb_release -r -s\r\n+ '[' '!' -e /home/user/.config/upstart/anbox.conf ']'\r\n+ initctl start anbox\r\ninitctl: Name \"com.ubuntu.Upstart\" does not exist\r\n\r\ntoo tired to keep playing with this now though"}],"action":{"name":"View Issue","url":"https://github.com/anbox/anbox-installer/issues/4#issuecomment-293543381"}}}

**Comment by GeitHub** [comment]
sudo apt install unity but still the same result. Okay, now I'm really calling it a night, lol,

**Comment by peterchibunna** [comment]
Ok. update:
I changed my distro version to 17.04
and ran the installer again. It got to the place where it was to start the service and failed. 
I rebooted. Tried to start the service: it failed.
I started the service manually but as a process (not in daemon mode)
And then the app runs ok now. No issues yet.

**Comment by vojta-horanek** [comment]
+1

**Comment by GeitHub** [comment]
@peterchibunna so you're running the KDE Neon User Edition now?

Also, just a quick Google of "initctl: Name "com.ubuntu.Upstart" does not exist" brings up a few bugzillas and it appears that this is a years long issue affecting LTS releases of Ubuntu (didn't look too much into it, though).

**Comment by peterchibunna** [comment]
Yes.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: GeitHubSent: Wednesday, 12 April 2017 20:10To: anbox/anbox-installerReply To: anbox/anbox-installerCc: peterchibunna; MentionSubject: Re: [anbox/anbox-installer] KDE Neon/Neon LTS Support (#4)@peterchibunna so you're running the KDE Neon User Edition now?
Also, just a quick Google of "initctl: Name "com.ubuntu.Upstart" does not exist" brings up a few bugzillas and it appears that this is a years long issue affecting LTS releases of Ubuntu (didn't look too much into it, though).

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anbox/anbox-installer","title":"anbox/anbox-installer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/anbox/anbox-installer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GeitHub in #4: @peterchibunna so you're running the KDE Neon User Edition now?\r\n\r\nAlso, just a quick Google of \"initctl: Name \"com.ubuntu.Upstart\" does not exist\" brings up a few bugzillas and it appears that this is a years long issue affecting LTS releases of Ubuntu (didn't look too much into it, though). "}],"action":{"name":"View Issue","url":"https://github.com/anbox/anbox-installer/issues/4#issuecomment-293678173"}}}

**Comment by peterchibunna** [comment]
KDE neon uses `systemd` so that path of `initctl` should not be followed.

**Comment by GeitHub** [comment]
Appreciate the recent patch to the installer adding neon support, but still not working on KDE Neon LTS (16.04). Though this is after lots of experimenting trying to get the installer to work, perhaps its working on a fresh install, can anyone confirm?

Here's my log

sudo snap refresh --edge anbox
snap "anbox" has no updates available
+ '[' '!' -e /etc/X11/Xsession.d/68anbox ']'
+ mkdir -p /home/user/.config/upstart
+ echo 'Installing upstart session job ..'
Installing upstart session job ..
+ cat
+ initctl start anbox
initctl: Name "com.ubuntu.Upstart" does not exist
+ true
+ mkdir -p /home/user/.config/systemd/user
+ echo 'Installing systemd user session service ..'
Installing systemd user session service ..
+ cat
+ systemctl --user daemon-reload
Failed to execute operation: Process org.freedesktop.systemd1 exited with status 1
+ true
+ systemctl --user enable --now anbox
Failed to execute operation: Process org.freedesktop.systemd1 exited with status 1
+ true
+ set +x

Done!

**Comment by sudopluto** [comment]
btw i added neon to the installer script, so i guess the systemd stuff needs to be figured out

**Comment by morphis** [comment]
Systemd support will come with the next updates we're about to release soon.

**Comment by morphis** [comment]
Better support for systemd landed now. Please try again with the latest version of the anbox-installer / anbox and reopen if still not fixed.

**Comment by GeitHub** [comment]
@morphis not sure how to re-open, but I'm still having the same bug

Fresh install of KDE Neon LTS, sudo apt update, sudo apt upgrade, sudo apt autoremove, reboot

snap install --classic anbox-installer && anbox-installer 
1
I AGREE

(should have copied the log here, but I didn't see any errors and it finished with Done!)

reboot

Click the newly created "Android in a Box" icon in Applications > Lost and Found
Nothing.

Open Terminal

anbox session-manager
[EE 2017-05-05 05:44:59] [session_manager.cpp:119@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded

same error when running:
/snap/bin/anbox session-manager

**Comment by morphis** [comment]
@GeitHub The error message is pretty clear. Either /dev/binder or /dev/ashmem doesn't exist. Please ensure the binder_linux and ashmem_linux kernel modules are correctly loaded.
